

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypass
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  web:
    build: .
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    env_file:  # <-- CORRECTED SYNTAX
      - .env.test

 # Add this new service for testing 🧪
  test:
    build: . # Build the same image as the 'web' service
    command: >
      sh -c "coverage run manage.py test && coverage report > coverage_report.txt"
    depends_on:
      - db
      - redis
    env_file:  # <-- CORRECTED SYNTAX
      - .env.test
    volumes:      # <-- ADD THIS SECTION
      - .:/app    # <-- ADD THIS LINE